// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'entities/album.dart';
import 'entities/artist.dart';
import 'entities/disc.dart';
import 'entities/genre.dart';
import 'entities/meta.dart';
import 'entities/song.dart';
import 'entities/track.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart';

Future<Song?> read({required String path}) =>
    RustLib.instance.api.crateApiSoftMetatagsRead(path: path);
