// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart';
import 'package:soft_metatags/src/bindings/api/entities/album.dart';
import 'package:soft_metatags/src/bindings/api/entities/artist.dart';
import 'package:soft_metatags/src/bindings/api/entities/disc.dart';
import 'package:soft_metatags/src/bindings/api/entities/genre.dart';
import 'package:soft_metatags/src/bindings/api/entities/meta.dart';
import 'package:soft_metatags/src/bindings/api/entities/song.dart';
import 'package:soft_metatags/src/bindings/api/entities/track.dart';
import 'package:soft_metatags/src/bindings/frb_generated.dart';

Future<Song?> read({required String path}) =>
    RustLib.instance.api.crateApiSoftMetatagsRead(path: path);
