// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unnecessary_import, non_constant_identifier_names, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'package:meta/meta.dart';
import 'package:soft_metatags/src/bindings/api/entities/album.dart';
import 'package:soft_metatags/src/bindings/api/entities/artist.dart';
import 'package:soft_metatags/src/bindings/api/entities/disc.dart';
import 'package:soft_metatags/src/bindings/api/entities/genre.dart';
import 'package:soft_metatags/src/bindings/api/entities/meta.dart';
import 'package:soft_metatags/src/bindings/api/entities/song.dart';
import 'package:soft_metatags/src/bindings/api/entities/track.dart';
import 'package:soft_metatags/src/bindings/api/soft_metatags.dart';
import 'package:soft_metatags/src/bindings/frb_generated.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Album dco_decode_album(dynamic raw);

  @protected
  Artist dco_decode_artist(dynamic raw);

  @protected
  Disc dco_decode_box_autoadd_disc(dynamic raw);

  @protected
  Meta dco_decode_box_autoadd_meta(dynamic raw);

  @protected
  Song dco_decode_box_autoadd_song(dynamic raw);

  @protected
  Track dco_decode_box_autoadd_track(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  Disc dco_decode_disc(dynamic raw);

  @protected
  Genre dco_decode_genre(dynamic raw);

  @protected
  List<Album> dco_decode_list_album(dynamic raw);

  @protected
  List<Artist> dco_decode_list_artist(dynamic raw);

  @protected
  List<Genre> dco_decode_list_genre(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Meta dco_decode_meta(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Disc? dco_decode_opt_box_autoadd_disc(dynamic raw);

  @protected
  Meta? dco_decode_opt_box_autoadd_meta(dynamic raw);

  @protected
  Song? dco_decode_opt_box_autoadd_song(dynamic raw);

  @protected
  Track? dco_decode_opt_box_autoadd_track(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  List<Album>? dco_decode_opt_list_album(dynamic raw);

  @protected
  List<Artist>? dco_decode_opt_list_artist(dynamic raw);

  @protected
  List<Genre>? dco_decode_opt_list_genre(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  Song dco_decode_song(dynamic raw);

  @protected
  Track dco_decode_track(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Album sse_decode_album(SseDeserializer deserializer);

  @protected
  Artist sse_decode_artist(SseDeserializer deserializer);

  @protected
  Disc sse_decode_box_autoadd_disc(SseDeserializer deserializer);

  @protected
  Meta sse_decode_box_autoadd_meta(SseDeserializer deserializer);

  @protected
  Song sse_decode_box_autoadd_song(SseDeserializer deserializer);

  @protected
  Track sse_decode_box_autoadd_track(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Disc sse_decode_disc(SseDeserializer deserializer);

  @protected
  Genre sse_decode_genre(SseDeserializer deserializer);

  @protected
  List<Album> sse_decode_list_album(SseDeserializer deserializer);

  @protected
  List<Artist> sse_decode_list_artist(SseDeserializer deserializer);

  @protected
  List<Genre> sse_decode_list_genre(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Meta sse_decode_meta(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Disc? sse_decode_opt_box_autoadd_disc(SseDeserializer deserializer);

  @protected
  Meta? sse_decode_opt_box_autoadd_meta(SseDeserializer deserializer);

  @protected
  Song? sse_decode_opt_box_autoadd_song(SseDeserializer deserializer);

  @protected
  Track? sse_decode_opt_box_autoadd_track(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  List<Album>? sse_decode_opt_list_album(SseDeserializer deserializer);

  @protected
  List<Artist>? sse_decode_opt_list_artist(SseDeserializer deserializer);

  @protected
  List<Genre>? sse_decode_opt_list_genre(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Song sse_decode_song(SseDeserializer deserializer);

  @protected
  Track sse_decode_track(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_album(Album self, SseSerializer serializer);

  @protected
  void sse_encode_artist(Artist self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_disc(Disc self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_meta(Meta self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_song(Song self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_track(Track self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_disc(Disc self, SseSerializer serializer);

  @protected
  void sse_encode_genre(Genre self, SseSerializer serializer);

  @protected
  void sse_encode_list_album(List<Album> self, SseSerializer serializer);

  @protected
  void sse_encode_list_artist(List<Artist> self, SseSerializer serializer);

  @protected
  void sse_encode_list_genre(List<Genre> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meta(Meta self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_disc(Disc? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_meta(Meta? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_song(Song? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_track(Track? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_album(List<Album>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_artist(List<Artist>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_genre(List<Genre>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song(Song self, SseSerializer serializer);

  @protected
  void sse_encode_track(Track self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;
}
