// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unnecessary_import, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, prefer_const_literals_to_create_immutables

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart';
import 'package:soft_metatags/src/bindings/api/entities/album.dart';
import 'package:soft_metatags/src/bindings/api/entities/artist.dart';
import 'package:soft_metatags/src/bindings/api/entities/disc.dart';
import 'package:soft_metatags/src/bindings/api/entities/genre.dart';
import 'package:soft_metatags/src/bindings/api/entities/meta.dart';
import 'package:soft_metatags/src/bindings/api/entities/song.dart';
import 'package:soft_metatags/src/bindings/api/entities/track.dart';
import 'package:soft_metatags/src/bindings/api/soft_metatags.dart';
import 'package:soft_metatags/src/bindings/frb_generated.dart';
import 'package:soft_metatags/src/bindings/frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  RustLib._();
  @internal
  static final instance = RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSoftMetatagsInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 823394672;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'soft_metatags',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSoftMetatagsInitApp();

  Future<Song?> crateApiSoftMetatagsRead({required String path});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSoftMetatagsInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSoftMetatagsInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSoftMetatagsInitAppConstMeta =>
      const TaskConstMeta(
        debugName: 'init_app',
        argNames: [],
      );

  @override
  Future<Song?> crateApiSoftMetatagsRead({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_song,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSoftMetatagsReadConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSoftMetatagsReadConstMeta => const TaskConstMeta(
    debugName: 'read',
    argNames: ['path'],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Album dco_decode_album(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Album(
      title: dco_decode_opt_String(arr[0]),
      artwork: dco_decode_opt_list_prim_u_8_strict(arr[1]),
      artists: dco_decode_opt_list_artist(arr[2]),
    );
  }

  @protected
  Artist dco_decode_artist(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Artist(
      name: dco_decode_opt_String(arr[0]),
      picture: dco_decode_opt_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  Disc dco_decode_box_autoadd_disc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_disc(raw);
  }

  @protected
  Meta dco_decode_box_autoadd_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_meta(raw);
  }

  @protected
  Song dco_decode_box_autoadd_song(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_song(raw);
  }

  @protected
  Track dco_decode_box_autoadd_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_track(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Disc dco_decode_disc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Disc(
      total: dco_decode_opt_box_autoadd_u_32(arr[0]),
      number: dco_decode_opt_box_autoadd_u_32(arr[1]),
    );
  }

  @protected
  Genre dco_decode_genre(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return Genre(
      name: dco_decode_opt_String(arr[0]),
    );
  }

  @protected
  List<Album> dco_decode_list_album(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_album).toList();
  }

  @protected
  List<Artist> dco_decode_list_artist(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_artist).toList();
  }

  @protected
  List<Genre> dco_decode_list_genre(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_genre).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Meta dco_decode_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 22)
      throw Exception('unexpected arr length: expect 22 but see ${arr.length}');
    return Meta(
      bpm: dco_decode_opt_box_autoadd_u_32(arr[0]),
      year: dco_decode_opt_box_autoadd_u_32(arr[1]),
      date: dco_decode_opt_box_autoadd_u_32(arr[2]),
      disc: dco_decode_opt_box_autoadd_disc(arr[3]),
      track: dco_decode_opt_box_autoadd_track(arr[4]),
      isrc: dco_decode_opt_String(arr[5]),
      mood: dco_decode_opt_String(arr[6]),
      title: dco_decode_opt_String(arr[7]),
      label: dco_decode_opt_String(arr[8]),
      lyrics: dco_decode_opt_String(arr[9]),
      comment: dco_decode_opt_String(arr[10]),
      barcode: dco_decode_opt_String(arr[11]),
      composer: dco_decode_opt_String(arr[12]),
      lyricist: dco_decode_opt_String(arr[13]),
      performer: dco_decode_opt_String(arr[14]),
      conductor: dco_decode_opt_String(arr[15]),
      copyright: dco_decode_opt_String(arr[16]),
      albums: dco_decode_opt_list_album(arr[17]),
      genres: dco_decode_opt_list_genre(arr[18]),
      encodedBy: dco_decode_opt_String(arr[19]),
      catalogNumber: dco_decode_opt_box_autoadd_u_32(arr[20]),
      artists: dco_decode_opt_list_artist(arr[21]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Disc? dco_decode_opt_box_autoadd_disc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_disc(raw);
  }

  @protected
  Meta? dco_decode_opt_box_autoadd_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_meta(raw);
  }

  @protected
  Song? dco_decode_opt_box_autoadd_song(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_song(raw);
  }

  @protected
  Track? dco_decode_opt_box_autoadd_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_track(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  List<Album>? dco_decode_opt_list_album(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_album(raw);
  }

  @protected
  List<Artist>? dco_decode_opt_list_artist(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_artist(raw);
  }

  @protected
  List<Genre>? dco_decode_opt_list_genre(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_genre(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  Song dco_decode_song(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Song(
      path: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      duration: dco_decode_u_64(arr[2]),
      meta: dco_decode_opt_box_autoadd_meta(arr[3]),
    );
  }

  @protected
  Track dco_decode_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Track(
      total: dco_decode_opt_box_autoadd_u_32(arr[0]),
      number: dco_decode_opt_box_autoadd_u_32(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Album sse_decode_album(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_title = sse_decode_opt_String(deserializer);
    final var_artwork = sse_decode_opt_list_prim_u_8_strict(deserializer);
    final var_artists = sse_decode_opt_list_artist(deserializer);
    return Album(title: var_title, artwork: var_artwork, artists: var_artists);
  }

  @protected
  Artist sse_decode_artist(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_name = sse_decode_opt_String(deserializer);
    final var_picture = sse_decode_opt_list_prim_u_8_strict(deserializer);
    return Artist(name: var_name, picture: var_picture);
  }

  @protected
  Disc sse_decode_box_autoadd_disc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return sse_decode_disc(deserializer);
  }

  @protected
  Meta sse_decode_box_autoadd_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return sse_decode_meta(deserializer);
  }

  @protected
  Song sse_decode_box_autoadd_song(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return sse_decode_song(deserializer);
  }

  @protected
  Track sse_decode_box_autoadd_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return sse_decode_track(deserializer);
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return sse_decode_u_32(deserializer);
  }

  @protected
  Disc sse_decode_disc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_total = sse_decode_opt_box_autoadd_u_32(deserializer);
    final var_number = sse_decode_opt_box_autoadd_u_32(deserializer);
    return Disc(total: var_total, number: var_number);
  }

  @protected
  Genre sse_decode_genre(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_name = sse_decode_opt_String(deserializer);
    return Genre(name: var_name);
  }

  @protected
  List<Album> sse_decode_list_album(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <Album>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_album(deserializer));
    }
    return ans_;
  }

  @protected
  List<Artist> sse_decode_list_artist(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <Artist>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_artist(deserializer));
    }
    return ans_;
  }

  @protected
  List<Genre> sse_decode_list_genre(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <Genre>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_genre(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Meta sse_decode_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_bpm = sse_decode_opt_box_autoadd_u_32(deserializer);
    final var_year = sse_decode_opt_box_autoadd_u_32(deserializer);
    final var_date = sse_decode_opt_box_autoadd_u_32(deserializer);
    final var_disc = sse_decode_opt_box_autoadd_disc(deserializer);
    final var_track = sse_decode_opt_box_autoadd_track(deserializer);
    final var_isrc = sse_decode_opt_String(deserializer);
    final var_mood = sse_decode_opt_String(deserializer);
    final var_title = sse_decode_opt_String(deserializer);
    final var_label = sse_decode_opt_String(deserializer);
    final var_lyrics = sse_decode_opt_String(deserializer);
    final var_comment = sse_decode_opt_String(deserializer);
    final var_barcode = sse_decode_opt_String(deserializer);
    final var_composer = sse_decode_opt_String(deserializer);
    final var_lyricist = sse_decode_opt_String(deserializer);
    final var_performer = sse_decode_opt_String(deserializer);
    final var_conductor = sse_decode_opt_String(deserializer);
    final var_copyright = sse_decode_opt_String(deserializer);
    final var_albums = sse_decode_opt_list_album(deserializer);
    final var_genres = sse_decode_opt_list_genre(deserializer);
    final var_encodedBy = sse_decode_opt_String(deserializer);
    final var_catalogNumber = sse_decode_opt_box_autoadd_u_32(deserializer);
    final var_artists = sse_decode_opt_list_artist(deserializer);
    return Meta(
      bpm: var_bpm,
      year: var_year,
      date: var_date,
      disc: var_disc,
      track: var_track,
      isrc: var_isrc,
      mood: var_mood,
      title: var_title,
      label: var_label,
      lyrics: var_lyrics,
      comment: var_comment,
      barcode: var_barcode,
      composer: var_composer,
      lyricist: var_lyricist,
      performer: var_performer,
      conductor: var_conductor,
      copyright: var_copyright,
      albums: var_albums,
      genres: var_genres,
      encodedBy: var_encodedBy,
      catalogNumber: var_catalogNumber,
      artists: var_artists,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_String(deserializer);
    } else {
      return null;
    }
  }

  @protected
  Disc? sse_decode_opt_box_autoadd_disc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_box_autoadd_disc(deserializer);
    } else {
      return null;
    }
  }

  @protected
  Meta? sse_decode_opt_box_autoadd_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_box_autoadd_meta(deserializer);
    } else {
      return null;
    }
  }

  @protected
  Song? sse_decode_opt_box_autoadd_song(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_box_autoadd_song(deserializer);
    } else {
      return null;
    }
  }

  @protected
  Track? sse_decode_opt_box_autoadd_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_box_autoadd_track(deserializer);
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_box_autoadd_u_32(deserializer);
    } else {
      return null;
    }
  }

  @protected
  List<Album>? sse_decode_opt_list_album(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_list_album(deserializer);
    } else {
      return null;
    }
  }

  @protected
  List<Artist>? sse_decode_opt_list_artist(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_list_artist(deserializer);
    } else {
      return null;
    }
  }

  @protected
  List<Genre>? sse_decode_opt_list_genre(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_list_genre(deserializer);
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_list_prim_u_8_strict(deserializer);
    } else {
      return null;
    }
  }

  @protected
  Song sse_decode_song(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_path = sse_decode_String(deserializer);
    final var_title = sse_decode_String(deserializer);
    final var_duration = sse_decode_u_64(deserializer);
    final var_meta = sse_decode_opt_box_autoadd_meta(deserializer);
    return Song(
      path: var_path,
      title: var_title,
      duration: var_duration,
      meta: var_meta,
    );
  }

  @protected
  Track sse_decode_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_total = sse_decode_opt_box_autoadd_u_32(deserializer);
    final var_number = sse_decode_opt_box_autoadd_u_32(deserializer);
    return Track(total: var_total, number: var_number);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_album(Album self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.artwork, serializer);
    sse_encode_opt_list_artist(self.artists, serializer);
  }

  @protected
  void sse_encode_artist(Artist self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.picture, serializer);
  }

  @protected
  void sse_encode_box_autoadd_disc(Disc self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_disc(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_meta(Meta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_meta(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_song(Song self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_song(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_track(Track self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_track(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_disc(Disc self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_u_32(self.total, serializer);
    sse_encode_opt_box_autoadd_u_32(self.number, serializer);
  }

  @protected
  void sse_encode_genre(Genre self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.name, serializer);
  }

  @protected
  void sse_encode_list_album(List<Album> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_album(item, serializer);
    }
  }

  @protected
  void sse_encode_list_artist(List<Artist> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_artist(item, serializer);
    }
  }

  @protected
  void sse_encode_list_genre(List<Genre> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_genre(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_meta(Meta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_u_32(self.bpm, serializer);
    sse_encode_opt_box_autoadd_u_32(self.year, serializer);
    sse_encode_opt_box_autoadd_u_32(self.date, serializer);
    sse_encode_opt_box_autoadd_disc(self.disc, serializer);
    sse_encode_opt_box_autoadd_track(self.track, serializer);
    sse_encode_opt_String(self.isrc, serializer);
    sse_encode_opt_String(self.mood, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.label, serializer);
    sse_encode_opt_String(self.lyrics, serializer);
    sse_encode_opt_String(self.comment, serializer);
    sse_encode_opt_String(self.barcode, serializer);
    sse_encode_opt_String(self.composer, serializer);
    sse_encode_opt_String(self.lyricist, serializer);
    sse_encode_opt_String(self.performer, serializer);
    sse_encode_opt_String(self.conductor, serializer);
    sse_encode_opt_String(self.copyright, serializer);
    sse_encode_opt_list_album(self.albums, serializer);
    sse_encode_opt_list_genre(self.genres, serializer);
    sse_encode_opt_String(self.encodedBy, serializer);
    sse_encode_opt_box_autoadd_u_32(self.catalogNumber, serializer);
    sse_encode_opt_list_artist(self.artists, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_disc(Disc? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_disc(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_meta(Meta? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_meta(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_song(Song? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_song(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_track(Track? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_track(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_album(List<Album>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_album(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_artist(
    List<Artist>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_artist(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_genre(List<Genre>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_genre(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_song(Song self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_u_64(self.duration, serializer);
    sse_encode_opt_box_autoadd_meta(self.meta, serializer);
  }

  @protected
  void sse_encode_track(Track self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_u_32(self.total, serializer);
    sse_encode_opt_box_autoadd_u_32(self.number, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
