// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'artist.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart';

// These functions are ignored because they are not marked as `pub`: `map_album`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_tag`

@immutable
class Album {
  final String? title;
  final Uint8List? artwork;
  final List<Artist>? artists;

  const Album({
    this.title,
    this.artwork,
    this.artists,
  });

  @override
  int get hashCode => title.hashCode ^ artwork.hashCode ^ artists.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Album &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artwork == other.artwork &&
          artists == other.artists;
}
