// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart';
import 'package:soft_metatags/src/bindings/api/entities/album.dart';
import 'package:soft_metatags/src/bindings/api/entities/artist.dart';
import 'package:soft_metatags/src/bindings/api/entities/disc.dart';
import 'package:soft_metatags/src/bindings/api/entities/genre.dart';
import 'package:soft_metatags/src/bindings/api/entities/track.dart';
import 'package:soft_metatags/src/bindings/frb_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_tag`

@immutable
class Meta {
  const Meta({
    this.bpm,
    this.year,
    this.date,
    this.disc,
    this.track,
    this.isrc,
    this.mood,
    this.title,
    this.label,
    this.lyrics,
    this.comment,
    this.barcode,
    this.composer,
    this.lyricist,
    this.performer,
    this.conductor,
    this.copyright,
    this.albums,
    this.genres,
    this.encodedBy,
    this.catalogNumber,
    this.artists,
  });
  final int? bpm;
  final int? year;
  final int? date;
  final Disc? disc;
  final Track? track;
  final String? isrc;
  final String? mood;
  final String? title;
  final String? label;
  final String? lyrics;
  final String? comment;
  final String? barcode;
  final String? composer;
  final String? lyricist;
  final String? performer;
  final String? conductor;
  final String? copyright;
  final List<Album>? albums;
  final List<Genre>? genres;
  final String? encodedBy;
  final int? catalogNumber;
  final List<Artist>? artists;

  @override
  int get hashCode =>
      bpm.hashCode ^
      year.hashCode ^
      date.hashCode ^
      disc.hashCode ^
      track.hashCode ^
      isrc.hashCode ^
      mood.hashCode ^
      title.hashCode ^
      label.hashCode ^
      lyrics.hashCode ^
      comment.hashCode ^
      barcode.hashCode ^
      composer.hashCode ^
      lyricist.hashCode ^
      performer.hashCode ^
      conductor.hashCode ^
      copyright.hashCode ^
      albums.hashCode ^
      genres.hashCode ^
      encodedBy.hashCode ^
      catalogNumber.hashCode ^
      artists.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Meta &&
          runtimeType == other.runtimeType &&
          bpm == other.bpm &&
          year == other.year &&
          date == other.date &&
          disc == other.disc &&
          track == other.track &&
          isrc == other.isrc &&
          mood == other.mood &&
          title == other.title &&
          label == other.label &&
          lyrics == other.lyrics &&
          comment == other.comment &&
          barcode == other.barcode &&
          composer == other.composer &&
          lyricist == other.lyricist &&
          performer == other.performer &&
          conductor == other.conductor &&
          copyright == other.copyright &&
          albums == other.albums &&
          genres == other.genres &&
          encodedBy == other.encodedBy &&
          catalogNumber == other.catalogNumber &&
          artists == other.artists;
}
