// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'album.dart';
import 'artist.dart';
import 'disc.dart';
import 'genre.dart';
import 'meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart';
import 'track.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`

class Song {
  final String path;
  final String title;
  final BigInt duration;
  final Meta? meta;

  const Song({
    required this.path,
    required this.title,
    required this.duration,
    this.meta,
  });

  @override
  int get hashCode =>
      path.hashCode ^ title.hashCode ^ duration.hashCode ^ meta.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Song &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          title == other.title &&
          duration == other.duration &&
          meta == other.meta;
}
