// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart';
import 'package:soft_metatags/src/bindings/api/entities/album.dart';
import 'package:soft_metatags/src/bindings/api/entities/artist.dart';
import 'package:soft_metatags/src/bindings/api/entities/disc.dart';
import 'package:soft_metatags/src/bindings/api/entities/genre.dart';
import 'package:soft_metatags/src/bindings/api/entities/meta.dart';
import 'package:soft_metatags/src/bindings/api/entities/track.dart';
import 'package:soft_metatags/src/bindings/frb_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`

class Song {
  const Song({
    required this.path,
    required this.title,
    required this.duration,
    this.meta,
  });
  final String path;
  final String title;
  final BigInt duration;
  final Meta? meta;

  @override
  int get hashCode =>
      path.hashCode ^ title.hashCode ^ duration.hashCode ^ meta.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Song &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          title == other.title &&
          duration == other.duration &&
          meta == other.meta;
}
