// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart';
import 'package:soft_metatags/src/bindings/frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_tag`

@immutable
class Track {
  const Track({
    this.total,
    this.number,
  });
  final int? total;
  final int? number;

  @override
  int get hashCode => total.hashCode ^ number.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Track &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          number == other.number;
}
