// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:soft_metatags/src/rust/frb_generated.dart';

Future<int> minimalAdder({required int a, required int b}) =>
    RustLib.instance.api.crateApiSoftMetatagsMinimalAdder(a: a, b: b);
